environment: dev
configurations:
  - profile: dev
    database:
      name: mysql
      url: 'root:123456@tcp(127.0.0.1:3306)/spm?charset=utf8mb4&parseTime=True&loc=Local'
    server:
      port: '8000'
    logger:
      level: debug
      path: '/home/abeir/doc/test'
      filename: demo
      maxAge: 1440h
      rotationTime: 24h
  - profile: prod
    database:
      name: mysql
      url: 'root:123456@tcp(127.0.0.1:3306)/spm?charset=utf8mb4&parseTime=True&loc=Local'
    server:
      port: '8000'
    logger:
      level: debug
      path: '/home/abeir/doc/test'
      filename: demo
      maxAge: 1440h
      rotationTime: 24h
  - profile: test
    database:
      name: sqlite3
      url: '/home/abeir/workspace/syberos/spm-serv/data.db'
    server:
      port: '8000'
    logger:
      level: debug
      path: '/home/abeir/doc/test'
      filename: demo
      maxAge: 1440h
      rotationTime: 24h
